pipeline {
  agent any
  environment {
    ANYPOINT= credentials('ANYPOINT')
}
  stages {
   stage('Build') {
    steps {
     withMaven(maven:'maven'){
	sh 'mvn -f mule-jenkins-pipeline/pom.xml clean install'

    }
  }
}
    stage('Deploy') {
     step{
      withMaven(maven:'maven'){ 
	sh 'mvn -f mule-jenkins-pipeline/pom.xml package deploy -Dusername=$ANYPOINT_USR  -Dpassword=$ANYPOINT_PWD --Denvironment=Sandbox -DmuleDeploy'

		 }
		}
	 }
    }
}